# Broadcasting en NumPy

Tres ejemplos reales de broadcasting pensados para alumnos básicos:

1. Broadcasting de dos vectores para crear una matriz
2. Broadcasting en un eje
3. Broadcasting en dos ejes

## Ejemplo 1 — Dos vectores → matriz

Coste total según precios y cantidades.

In [3]:
import numpy as np

precios = np.array([2.5, 4.0, 6.0])
cantidades = np.array([10, 20, 15, 30, 25])

coste_total = precios[:, np.newaxis] * cantidades

coste_total

array([[ 25. ,  50. ,  37.5,  75. ,  62.5],
       [ 40. ,  80. ,  60. , 120. , 100. ],
       [ 60. , 120. ,  90. , 180. , 150. ]])

## Ejemplo 2 — Broadcasting en un eje

Ventas de varias tiendas con impuesto por tienda.

In [4]:
ventas = np.array([
    [100, 120, 90, 110, 130],
    [80, 95, 85, 100, 105],
    [200, 210, 190, 205, 215]
])

impuestos = np.array([1.10, 1.08, 1.21])

ventas_con_impuesto = ventas * impuestos[:, np.newaxis]

ventas_con_impuesto

array([[110.  , 132.  ,  99.  , 121.  , 143.  ],
       [ 86.4 , 102.6 ,  91.8 , 108.  , 113.4 ],
       [242.  , 254.1 , 229.9 , 248.05, 260.15]])

## Ejemplo 3 — Broadcasting en dos ejes

Modificación de una imagen aplicando factores por fila y columna.

In [2]:
imagen = np.array([
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160],
    [170, 180, 190, 200]
])

brillo_fila = np.array([0.8, 1.0, 1.1, 1.3])
contraste_columna = np.array([1.0, 0.9, 1.1, 1.2])

imagen_modificada = imagen * brillo_fila[:, np.newaxis] * contraste_columna

imagen_modificada

array([[ 40. ,  43.2,  61.6,  76.8],
       [ 90. ,  90. , 121. , 144. ],
       [143. , 138.6, 181.5, 211.2],
       [221. , 210.6, 271.7, 312. ]])