# Vistas y Copias en NumPy

## ¿Por qué es importante entender esto?

Cuando trabajamos con arrays grandes en NumPy, es crucial entender cuándo estamos creando **copias** (que duplican memoria) y cuándo estamos creando **vistas** (que comparten memoria). Esto puede afectar significativamente:

- **Rendimiento**: Las copias consumen memoria y tiempo
- **Comportamiento**: Modificar una vista afecta al array original, modificar una copia no
- **Uso de memoria**: En datasets grandes, duplicar memoria puede ser problemático

In [1]:
import numpy as np

## 1. Verificar si es Vista o Copia

NumPy proporciona funciones para verificar si un array es una vista o una copia.

In [2]:
def es_vista_o_copia(original, nuevo):
    """
    Verifica si un array es una vista o copia del original.
    """
    print(f"¿Comparten memoria? {np.shares_memory(original, nuevo)}")
    print(f"¿Es vista? {nuevo.base is original or nuevo.base is not None}")
    print(f"Base del nuevo array: {nuevo.base}")
    print(f"ID del original: {id(original)}")
    print(f"ID del nuevo: {id(nuevo)}")
    print(f"¿Mismo objeto? {original is nuevo}")
    print()

# Ejemplo básico
arr = np.array([1, 2, 3, 4, 5])
print("=== ARRAY ORIGINAL ===")
print(f"Array: {arr}")
print(f"ID: {id(arr)}")
print()

# Vista
vista = arr[:]
print("=== VISTA (arr[:]) ===")
es_vista_o_copia(arr, vista)

# Copia
copia = arr.copy()
print("=== COPIA (arr.copy()) ===")
es_vista_o_copia(arr, copia)

=== ARRAY ORIGINAL ===
Array: [1 2 3 4 5]
ID: 4466031952

=== VISTA (arr[:]) ===
¿Comparten memoria? True
¿Es vista? True
Base del nuevo array: [1 2 3 4 5]
ID del original: 4466031952
ID del nuevo: 4466031088
¿Mismo objeto? False

=== COPIA (arr.copy()) ===
¿Comparten memoria? False
¿Es vista? False
Base del nuevo array: None
ID del original: 4466031952
ID del nuevo: 4466031184
¿Mismo objeto? False



## 2. Operaciones que Crean Vistas

Estas operaciones **NO duplican memoria**, crean vistas que comparten datos.

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("=== SLICING (crea vista) ===")
vista_slice = arr[2:7]
print(f"Original: {arr}")
print(f"Vista [2:7]: {vista_slice}")
print(f"¿Comparten memoria? {np.shares_memory(arr, vista_slice)}")
print()

# Modificar la vista afecta al original
print("Modificando vista_slice[0] = 99...")
vista_slice[0] = 99
print(f"Original después: {arr}")
print(f"Vista después: {vista_slice}\n")

# Resetear para siguiente ejemplo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("=== TRANSPOSE (crea vista) ===")
matriz = arr.reshape(2, 5)
transpuesta = matriz.T
print(f"Matriz:\n{matriz}")
print(f"Transpuesta:\n{transpuesta}")
print(f"¿Comparten memoria? {np.shares_memory(matriz, transpuesta)}")
print()

print("=== RESHAPE (crea vista si es posible) ===")
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)
print(f"1D: {arr_1d}")
print(f"2D:\n{arr_2d}")
print(f"¿Comparten memoria? {np.shares_memory(arr_1d, arr_2d)}\n")

print("=== RAVEL (crea vista) ===")
matriz = np.array([[1, 2, 3], [4, 5, 6]])
aplanado = matriz.ravel()
print(f"Matriz:\n{matriz}")
print(f"Aplanado: {aplanado}")
print(f"¿Comparten memoria? {np.shares_memory(matriz, aplanado)}")

=== SLICING (crea vista) ===
Original: [ 1  2  3  4  5  6  7  8  9 10]
Vista [2:7]: [3 4 5 6 7]
¿Comparten memoria? True

Modificando vista_slice[0] = 99...
Original después: [ 1  2 99  4  5  6  7  8  9 10]
Vista después: [99  4  5  6  7]

=== TRANSPOSE (crea vista) ===
Matriz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transpuesta:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
¿Comparten memoria? True

=== RESHAPE (crea vista si es posible) ===
1D: [1 2 3 4 5 6]
2D:
[[1 2 3]
 [4 5 6]]
¿Comparten memoria? True

=== RAVEL (crea vista) ===
Matriz:
[[1 2 3]
 [4 5 6]]
Aplanado: [1 2 3 4 5 6]
¿Comparten memoria? True


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
copia = arr[1:3].copy()
copia[0] = 99
print(copia, arr)

## 3. Operaciones que Crean Copias

Estas operaciones **SÍ duplican memoria**, crean arrays independientes.

In [6]:
print("=== Fancy indexing (crea copia) ===")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0, 2, 4, 6]
seleccion = arr[indices]
print(f"Original: {arr}")
print(f"Selección con índices [0, 2, 4, 6]: {seleccion}")
print(f"¿Comparten memoria? {np.shares_memory(arr, seleccion)}")
seleccion[0] = 99
print(f"Después de modificar selección:")
print(f"Original: {arr} (no cambió)")
print(f"Selección: {seleccion}")

=== Fancy indexing (crea copia) ===
Original: [ 1  2  3  4  5  6  7  8  9 10]
Selección con índices [0, 2, 4, 6]: [1 3 5 7]
¿Comparten memoria? False
Después de modificar selección:
Original: [ 1  2  3  4  5  6  7  8  9 10] (no cambió)
Selección: [99  3  5  7]


## 4. Comparación de Uso de Memoria

Veamos la diferencia en memoria entre vistas y copias.

In [13]:
def mostrar_memoria(arr, nombre):
    """Muestra el tamaño en memoria de un array"""
    tamaño_bytes = arr.nbytes
    tamaño_mb = tamaño_bytes / (1024 * 1024)
    print(f"{nombre}:")
    print(f"  Shape: {arr.shape}")
    print(f"  Tamaño: {tamaño_bytes:,} bytes ({tamaño_mb:.4f} MB)")
    print(f"  ID: {id(arr)}")
    print()

# Crear un array grande
arr = np.random.rand(1000, 1000)
mostrar_memoria(arr, "Array")

Array:
  Shape: (1000, 1000)
  Tamaño: 8,000,000 bytes (7.6294 MB)
  ID: 4572016976



## 5. Dtypes y Uso de Memoria

El tipo de datos (dtype) determina cuánta memoria usa cada elemento del array. Elegir el dtype correcto puede ahorrar mucha memoria.

In [24]:
# Crear arrays del mismo tamaño pero con diferentes dtypes
arr_int64 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
arr_int32 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_int16 = np.array([1, 2, 3, 4, 5], dtype=np.int16)
arr_int8 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
arr_float64 = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float64)
arr_float32 = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float32)

print("=== COMPARACIÓN DE DTYPES ===")
print(f"int64: {arr_int64.nbytes} bytes, dtype: {arr_int64.dtype}")
print(f"int32: {arr_int32.nbytes} bytes, dtype: {arr_int32.dtype}")
print(f"int16: {arr_int16.nbytes} bytes, dtype: {arr_int16.dtype}")
print(f"int8:  {arr_int8.nbytes} bytes, dtype: {arr_int8.dtype}")
print(f"float64: {arr_float64.nbytes} bytes, dtype: {arr_float64.dtype}")
print(f"float32: {arr_float32.nbytes} bytes, dtype: {arr_float32.dtype}")
print()

# Ejemplo con array grande
print("=== IMPACTO EN ARRAYS GRANDES ===")
tamaño = (1920, 1080)
arr_int64_grande = np.random.randint(0, 100, size=tamaño, dtype=np.int16)
arr_float64_grande = np.random.rand(*tamaño).astype(np.float64)
arr_float32_grande = np.random.rand(*tamaño).astype(np.float32)

print(f"Array {tamaño[0]}x{tamaño[1]} elementos:")
print(f"  int16:   {arr_int64_grande.nbytes / (1024*1024):.2f} MB")
print(f"  float64: {arr_float64_grande.nbytes / (1024*1024):.2f} MB")
print(f"  float32: {arr_float32_grande.nbytes / (1024*1024):.2f} MB")


=== COMPARACIÓN DE DTYPES ===
int64: 40 bytes, dtype: int64
int32: 20 bytes, dtype: int32
int16: 10 bytes, dtype: int16
int8:  5 bytes, dtype: int8
float64: 40 bytes, dtype: float64
float32: 20 bytes, dtype: float32

=== IMPACTO EN ARRAYS GRANDES ===
Array 1920x1080 elementos:
  int16:   3.96 MB
  float64: 15.82 MB
  float32: 7.91 MB
