# Introducción a NumPy

NumPy (Numerical Python) es la biblioteca fundamental para computación científica en Python. Proporciona:
- Arrays multidimensionales eficientes
- Funciones matemáticas de alto nivel
- Herramientas para trabajar con arrays
- Operaciones vectorizadas (más rápidas que loops en Python)

## ¿Por qué NumPy?

- **Velocidad**: Operaciones vectorizadas escritas en C
- **Memoria**: Almacenamiento eficiente de datos
- **Funcionalidad**: Amplio conjunto de funciones matemáticas

In [ ]:
import numpy as np
import time
from functools import wraps

def medir_tiempo(func):
    """
    Decorador para medir el tiempo de ejecución de una función.
    
    Returns:
        tuple: (resultado de la función, tiempo en segundos)
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        resultado = func(*args, **kwargs)
        tiempo_ejecucion = time.time() - start
        return resultado, tiempo_ejecucion
    return wrapper

# Comparación de velocidad: Python list vs NumPy array
python_list = list(range(1000000))
numpy_array = np.array(range(1000000))

# Multiplicar por 2
@medir_tiempo
def multiplicar_python_list(python_list):
    return [x * 2 for x in python_list]

@medir_tiempo
def multiplicar_numpy_array(numpy_array):
    return numpy_array * 2

result_python, time_python = multiplicar_python_list(python_list)
result_numpy, time_numpy = multiplicar_numpy_array(numpy_array)

print(f"Python list: {time_python:.4f} segundos")
print(f"NumPy array: {time_numpy:.4f} segundos")
print(f"NumPy es {time_python/time_numpy:.1f}x más rápido")

Python list: 0.0126 segundos
NumPy array: 0.0012 segundos
NumPy es 10.5x más rápido


## 1. Creación de Arrays

In [ ]:
# Desde una lista de Python
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr1)
print("Tipo:", type(arr1))
print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)

# Array 2D (matriz)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 2D:")
print(arr2d)
print("Shape:", arr2d.shape)  # (filas, columnas)
print("Dimensiones:", arr2d.ndim)

Array 1D: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Shape: (5,)
Dtype: int64

Array 2D:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensiones: 2


In [ ]:
# Arrays con valores iniciales
zeros = np.zeros((3, 4))  # Matriz de ceros 3x4
ones = np.ones((2, 3))     # Matriz de unos 2x3
full = np.full((2, 2), 7)  # Matriz llena de 7s
identity = np.eye(3)       # Matriz identidad 3x3
arange = np.arange(0, 10, 2)  # Similar a range(): [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 valores equiespaciados entre 0 y 1

print("Zeros (3x4):")
print(zeros)
print("\nOnes (2x3):")
print(ones)
print("\nFull (2x2 con 7s):")
print(full)
print("\nIdentity (3x3):")
print(identity)
print("\nArange:", arange)
print("Linspace:", linspace)

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Full (2x2 con 7s):
[[7 7]
 [7 7]]

Identity (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Arrays aleatorios
random_arr = np.random.rand(3, 3)  # Valores entre 0 y 1
random_int = np.random.randint(0, 10, size=(2, 4))  # Enteros entre 0 y 9
normal_dist = np.random.randn(3,3) * 5 + 5

print("Random (0-1):")
print(random_arr)
print("\nRandom integers (0-9):")
print(random_int)
print("\nNormal distribution:")
print(normal_dist)

Random (0-1):
[[0.21020713 0.54804355 0.96247727]
 [0.33029579 0.92801976 0.25235747]
 [0.73681519 0.31063903 0.27279697]]

Random integers (0-9):
[[9 8 6 9]
 [4 9 2 6]]

Normal distribution:
[[ 6.41327665  8.09045673  3.2630152 ]
 [ 1.26066738  4.85678375  1.63164998]
 [-0.2185876  -1.22537673  0.70926951]]


## 2. Indexación y Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Indexación (similar a listas de Python)
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])
print("Slice [1:4]:", arr[1:4])  # [20, 30, 40]
print("Todos los pares [::2]:", arr[::2])  # [10, 30, 50]

Primer elemento: 10
Último elemento: 50
Slice [1:4]: [20 30 40]
Todos los pares [::2]: [10 30 50]


In [ ]:
# Indexación en arrays 2D
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz completa:")
print(matrix)
print("\nElemento [1, 2]:", matrix[1, 2])  # Fila 1, columna 2
print("Primera fila:", matrix[0, :])
print("Primera columna:", matrix[:, 0])
print("Submatriz [0:2, 1:3]:")
print(matrix[0:2, 1:3])

Matriz completa:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento [1, 2]: 6
Primera fila: [1 2 3]
Primera columna: [1 4 7]
Submatriz [0:2, 1:3]:
[[2 3]
 [5 6]]


In [ ]:
# Indexación booleana (muy útil!)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5
print("Array original:", arr)
print("Máscara (arr > 5):", mask)
print("Elementos > 5:", arr[mask])
print("Elementos pares:", arr[arr % 2 == 0])

Array original: [ 1  2  3  4  5  6  7  8  9 10]
Máscara (arr > 5): [False False False False False  True  True  True  True  True]
Elementos > 5: [ 6  7  8  9 10]
Elementos pares: [ 2  4  6  8 10]


## 3. Operaciones Matemáticas

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Operaciones elemento a elemento
print("Suma:", a + b)
print("Resta:", b - a)
print("Multiplicación:", a * b)
print("División:", b / a)
print("Potencia:", a ** 2)
print("Raíz cuadrada:", np.sqrt(a))

Suma: [ 6  8 10 12]
Resta: [4 4 4 4]
Multiplicación: [ 5 12 21 32]
División: [5.         3.         2.33333333 2.        ]
Potencia: [ 1  4  9 16]
Raíz cuadrada: [1.         1.41421356 1.73205081 2.        ]


In [ ]:
# Operaciones con escalares (broadcasting)
arr = np.array([1, 2, 3, 4])
print("Array:", arr)
print("Sumar 10:", arr + 10)
print("Multiplicar por 3:", arr * 3)
print("Elevar al cuadrado:", arr ** 2)

Array: [1 2 3 4]
Sumar 10: [11 12 13 14]
Multiplicar por 3: [ 3  6  9 12]
Elevar al cuadrado: [ 1  4  9 16]


In [ ]:
# Funciones estadísticas
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Datos:", data)
print("Suma:", np.sum(data))
print("Promedio:", np.mean(data))
print("Mediana:", np.median(data))
print("Desviación estándar:", np.std(data))
print("Mínimo:", np.min(data))
print("Máximo:", np.max(data))
print("Percentil 75:", np.percentile(data, 75))

Datos: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Promedio: 5.5
Mediana: 5.5
Desviación estándar: 2.8722813232690143
Mínimo: 1
Máximo: 10
Percentil 75: 7.75


## 4. Operaciones con Arrays Multidimensionales

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:")
print(matrix)

# Operaciones por fila o columna
print("\nSuma por filas (axis=1):", np.sum(matrix, axis=1))
print("Suma por columnas (axis=0):", np.sum(matrix, axis=0))
print("Promedio por filas:", np.mean(matrix, axis=1))
print("Promedio por columnas:", np.mean(matrix, axis=0))

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma por filas (axis=1): [ 6 15 24]
Suma por columnas (axis=0): [12 15 18]
Promedio por filas: [2. 5. 8.]
Promedio por columnas: [4. 5. 6.]


In [ ]:
# Producto matricial (dot product)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matriz A:")
print(a)
print("\nMatriz B:")
print(b)
print("\nProducto matricial (A @ B):")
print(a @ b)  # O np.dot(a, b)
print("\nMultiplicación elemento a elemento (A * B):")
print(a * b)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Producto matricial (A @ B):
[[19 22]
 [43 50]]

Multiplicación elemento a elemento (A * B):
[[ 5 12]
 [21 32]]


## 5. Reshape y Manipulación de Arrays

In [ ]:
arr = np.arange(12)
print("Array 1D:", arr)

# Reshape a 2D
matrix = arr.reshape(3, 4)
print("\nReshape a (3, 4):")
print(matrix)

# Flatten (aplanar)
flattened = matrix.flatten()
print("\nAplanado:", flattened)

# Transponer
transposed = matrix.T
print("\nTranspuesta:")
print(transposed)

Array 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape a (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Aplanado: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpuesta:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Concatenar arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Concatenar horizontalmente:", np.concatenate([a, b]))
print("Apilar verticalmente:")
print(np.vstack([a, b]))
print("Apilar horizontalmente:")
print(np.hstack([a, b]))

Concatenar horizontalmente: [1 2 3 4 5 6]
Apilar verticalmente:
[[1 2 3]
 [4 5 6]]
Apilar horizontalmente:
[1 2 3 4 5 6]


## 6. Broadcasting

El broadcasting permite que NumPy realice operaciones entre arrays de diferentes formas de manera eficiente.

In [ ]:
# Ejemplo 1: Array 2D + Array 1D
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

print("Matriz:")
print(matrix)
print("\nVector:", vector)
print("\nSuma (broadcasting):")
print(matrix + vector)  # Suma el vector a cada fila

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector: [10 20 30]

Suma (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


## 8. Comparación: Python Puro vs NumPy

Veamos la diferencia de rendimiento y legibilidad.

In [ ]:
# Tarea: Calcular la distancia euclidiana entre dos vectores

# Python puro
@medir_tiempo
def distancia_python(v1, v2):
    suma = 0
    for i in range(len(v1)):
        suma += (v1[i] - v2[i]) ** 2
    return suma ** 0.5

# NumPy
@medir_tiempo
def distancia_numpy(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))

# O más simple aún:
@medir_tiempo
def distancia_numpy_simple(v1, v2):
    return np.linalg.norm(v1 - v2)

# Vectores grandes para comparar rendimiento
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

_, tiempo_py = distancia_python(v1, v2)
_, tiempo_np = distancia_numpy(v1, v2)
_, tiempo_np_simple = distancia_numpy_simple(v1, v2)

print(f"Tiempo Python puro: {tiempo_py:.6f} segundos")
print(f"Tiempo NumPy: {tiempo_np:.6f} segundos")
print(f"Tiempo NumPy (norm): {tiempo_np_simple:.6f} segundos")
print()
print(f"NumPy es {tiempo_py/tiempo_np:.1f}x más rápido que Python puro")
print(f"NumPy (norm) es {tiempo_py/tiempo_np_simple:.1f}x más rápido que Python puro")

=== VERIFICACIÓN DE RESULTADOS ===
Distancia (Python): 11.180340
Distancia (NumPy): 11.180340
Distancia (NumPy simple): 11.180340

=== COMPARACIÓN DE RENDIMIENTO (vectores de 1,000,000 elementos) ===
Tiempo Python puro: 0.155931 segundos
Tiempo NumPy: 0.002318 segundos
Tiempo NumPy (norm): 0.000249 segundos

⚡ NumPy es 67.3x más rápido que Python puro
⚡ NumPy (norm) es 626.5x más rápido que Python puro


In [ ]:
arr = np.array([1, 5, 3, 8, 2, 7])
resultado = np.where(arr > 5, arr * 2, arr)  # Si > 5, multiplica por 2, sino mantiene valor
print(resultado)

[ 1  5  3 16  2 14]
